// <auto-generated />
using DatosIonosfericos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatosIonosfericos.Presentacion.Migrations
{
    [DbContext(typeof(IonosferaContext))]
    [Migration("20230912205725_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatosIonosfericos.Data.Record", b =>
                {
                    b.Property<string>("dt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("aip_b0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_b1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_d1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_deln_ve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_ewidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_foe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_fof1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_fof2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_h_ve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_hme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_hmf1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_hmf2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aip_yme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evaluated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fof1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("fof1_eval")
                        .HasColumnType("bit");

                    b.Property<string>("fof2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("fof2_eval")
                        .HasColumnType("bit");

                    b.Property<string>("fof2_med_27_days")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fromfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ftes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ftes_eval")
                        .HasColumnType("bit");

                    b.Property<string>("fxi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("fxi_eval")
                        .HasColumnType("bit");

                    b.Property<string>("h_es")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("h_es_eval")
                        .HasColumnType("bit");

                    b.Property<string>("m3000f2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("m3000f2_eval")
                        .HasColumnType("bit");

                    b.Property<string>("modified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("muf3000f2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("muf3000f2_eval")
                        .HasColumnType("bit");

                    b.Property<string>("producer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tec_bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tec_top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dt");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
